#############################################################################
# Makefile for building: PDtools-X10
# Generated by qmake (3.0) (Qt 5.4.1)
# Project:  PDtools-X10.pro
# Template: subdirs
# Command: /home/sigve/Qt/5.4/gcc_64/bin/qmake -o Makefile PDtools-X10.pro
#############################################################################

MAKEFILE      = Makefile

first: make_first
QMAKE         = /home/sigve/Qt/5.4/gcc_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = PDtools-X101.0.0
DISTDIR = /home/sigve/Dropbox/Programs/PDtools/PDtools/.tmp/PDtools-X101.0.0
SUBTARGETS    =  \
		sub-src \
		sub-tests \
		sub-benchmarks


sub-src-qmake_all:  FORCE
	@test -d src/ || mkdir -p src/
	cd src/ && $(QMAKE) /home/sigve/Dropbox/Programs/PDtools/PDtools/src/src.pro -o Makefile
	cd src/ && $(MAKE) -f Makefile qmake_all
sub-src: FORCE
	@test -d src/ || mkdir -p src/
	cd src/ && ( test -e Makefile || $(QMAKE) /home/sigve/Dropbox/Programs/PDtools/PDtools/src/src.pro -o Makefile ) && $(MAKE) -f Makefile
sub-src-make_first-ordered: FORCE
	@test -d src/ || mkdir -p src/
	cd src/ && ( test -e Makefile || $(QMAKE) /home/sigve/Dropbox/Programs/PDtools/PDtools/src/src.pro -o Makefile ) && $(MAKE) -f Makefile 
sub-src-make_first: FORCE
	@test -d src/ || mkdir -p src/
	cd src/ && ( test -e Makefile || $(QMAKE) /home/sigve/Dropbox/Programs/PDtools/PDtools/src/src.pro -o Makefile ) && $(MAKE) -f Makefile 
sub-src-all-ordered: FORCE
	@test -d src/ || mkdir -p src/
	cd src/ && ( test -e Makefile || $(QMAKE) /home/sigve/Dropbox/Programs/PDtools/PDtools/src/src.pro -o Makefile ) && $(MAKE) -f Makefile all
sub-src-all: FORCE
	@test -d src/ || mkdir -p src/
	cd src/ && ( test -e Makefile || $(QMAKE) /home/sigve/Dropbox/Programs/PDtools/PDtools/src/src.pro -o Makefile ) && $(MAKE) -f Makefile all
sub-src-clean-ordered: FORCE
	@test -d src/ || mkdir -p src/
	cd src/ && ( test -e Makefile || $(QMAKE) /home/sigve/Dropbox/Programs/PDtools/PDtools/src/src.pro -o Makefile ) && $(MAKE) -f Makefile clean
sub-src-clean: FORCE
	@test -d src/ || mkdir -p src/
	cd src/ && ( test -e Makefile || $(QMAKE) /home/sigve/Dropbox/Programs/PDtools/PDtools/src/src.pro -o Makefile ) && $(MAKE) -f Makefile clean
sub-src-distclean-ordered: FORCE
	@test -d src/ || mkdir -p src/
	cd src/ && ( test -e Makefile || $(QMAKE) /home/sigve/Dropbox/Programs/PDtools/PDtools/src/src.pro -o Makefile ) && $(MAKE) -f Makefile distclean
sub-src-distclean: FORCE
	@test -d src/ || mkdir -p src/
	cd src/ && ( test -e Makefile || $(QMAKE) /home/sigve/Dropbox/Programs/PDtools/PDtools/src/src.pro -o Makefile ) && $(MAKE) -f Makefile distclean
sub-src-install_subtargets-ordered: FORCE
	@test -d src/ || mkdir -p src/
	cd src/ && ( test -e Makefile || $(QMAKE) /home/sigve/Dropbox/Programs/PDtools/PDtools/src/src.pro -o Makefile ) && $(MAKE) -f Makefile install
sub-src-install_subtargets: FORCE
	@test -d src/ || mkdir -p src/
	cd src/ && ( test -e Makefile || $(QMAKE) /home/sigve/Dropbox/Programs/PDtools/PDtools/src/src.pro -o Makefile ) && $(MAKE) -f Makefile install
sub-src-uninstall_subtargets-ordered: FORCE
	@test -d src/ || mkdir -p src/
	cd src/ && ( test -e Makefile || $(QMAKE) /home/sigve/Dropbox/Programs/PDtools/PDtools/src/src.pro -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-src-uninstall_subtargets: FORCE
	@test -d src/ || mkdir -p src/
	cd src/ && ( test -e Makefile || $(QMAKE) /home/sigve/Dropbox/Programs/PDtools/PDtools/src/src.pro -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-tests-qmake_all: sub-src-qmake_all FORCE
	@test -d tests/ || mkdir -p tests/
	cd tests/ && $(QMAKE) /home/sigve/Dropbox/Programs/PDtools/PDtools/tests/tests.pro -o Makefile
	cd tests/ && $(MAKE) -f Makefile qmake_all
sub-tests: FORCE
	@test -d tests/ || mkdir -p tests/
	cd tests/ && ( test -e Makefile || $(QMAKE) /home/sigve/Dropbox/Programs/PDtools/PDtools/tests/tests.pro -o Makefile ) && $(MAKE) -f Makefile
sub-tests-make_first-ordered: sub-src-make_first-ordered  FORCE
	@test -d tests/ || mkdir -p tests/
	cd tests/ && ( test -e Makefile || $(QMAKE) /home/sigve/Dropbox/Programs/PDtools/PDtools/tests/tests.pro -o Makefile ) && $(MAKE) -f Makefile 
sub-tests-make_first: FORCE
	@test -d tests/ || mkdir -p tests/
	cd tests/ && ( test -e Makefile || $(QMAKE) /home/sigve/Dropbox/Programs/PDtools/PDtools/tests/tests.pro -o Makefile ) && $(MAKE) -f Makefile 
sub-tests-all-ordered: sub-src-all-ordered  FORCE
	@test -d tests/ || mkdir -p tests/
	cd tests/ && ( test -e Makefile || $(QMAKE) /home/sigve/Dropbox/Programs/PDtools/PDtools/tests/tests.pro -o Makefile ) && $(MAKE) -f Makefile all
sub-tests-all: FORCE
	@test -d tests/ || mkdir -p tests/
	cd tests/ && ( test -e Makefile || $(QMAKE) /home/sigve/Dropbox/Programs/PDtools/PDtools/tests/tests.pro -o Makefile ) && $(MAKE) -f Makefile all
sub-tests-clean-ordered: sub-src-clean-ordered  FORCE
	@test -d tests/ || mkdir -p tests/
	cd tests/ && ( test -e Makefile || $(QMAKE) /home/sigve/Dropbox/Programs/PDtools/PDtools/tests/tests.pro -o Makefile ) && $(MAKE) -f Makefile clean
sub-tests-clean: FORCE
	@test -d tests/ || mkdir -p tests/
	cd tests/ && ( test -e Makefile || $(QMAKE) /home/sigve/Dropbox/Programs/PDtools/PDtools/tests/tests.pro -o Makefile ) && $(MAKE) -f Makefile clean
sub-tests-distclean-ordered: sub-src-distclean-ordered  FORCE
	@test -d tests/ || mkdir -p tests/
	cd tests/ && ( test -e Makefile || $(QMAKE) /home/sigve/Dropbox/Programs/PDtools/PDtools/tests/tests.pro -o Makefile ) && $(MAKE) -f Makefile distclean
sub-tests-distclean: FORCE
	@test -d tests/ || mkdir -p tests/
	cd tests/ && ( test -e Makefile || $(QMAKE) /home/sigve/Dropbox/Programs/PDtools/PDtools/tests/tests.pro -o Makefile ) && $(MAKE) -f Makefile distclean
sub-tests-install_subtargets-ordered: sub-src-install_subtargets-ordered  FORCE
	@test -d tests/ || mkdir -p tests/
	cd tests/ && ( test -e Makefile || $(QMAKE) /home/sigve/Dropbox/Programs/PDtools/PDtools/tests/tests.pro -o Makefile ) && $(MAKE) -f Makefile install
sub-tests-install_subtargets: FORCE
	@test -d tests/ || mkdir -p tests/
	cd tests/ && ( test -e Makefile || $(QMAKE) /home/sigve/Dropbox/Programs/PDtools/PDtools/tests/tests.pro -o Makefile ) && $(MAKE) -f Makefile install
sub-tests-uninstall_subtargets-ordered: sub-src-uninstall_subtargets-ordered  FORCE
	@test -d tests/ || mkdir -p tests/
	cd tests/ && ( test -e Makefile || $(QMAKE) /home/sigve/Dropbox/Programs/PDtools/PDtools/tests/tests.pro -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-tests-uninstall_subtargets: FORCE
	@test -d tests/ || mkdir -p tests/
	cd tests/ && ( test -e Makefile || $(QMAKE) /home/sigve/Dropbox/Programs/PDtools/PDtools/tests/tests.pro -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-benchmarks-qmake_all: sub-tests-qmake_all FORCE
	@test -d benchmarks/ || mkdir -p benchmarks/
	cd benchmarks/ && $(QMAKE) /home/sigve/Dropbox/Programs/PDtools/PDtools/benchmarks/benchmarks.pro -o Makefile
	cd benchmarks/ && $(MAKE) -f Makefile qmake_all
sub-benchmarks: FORCE
	@test -d benchmarks/ || mkdir -p benchmarks/
	cd benchmarks/ && ( test -e Makefile || $(QMAKE) /home/sigve/Dropbox/Programs/PDtools/PDtools/benchmarks/benchmarks.pro -o Makefile ) && $(MAKE) -f Makefile
sub-benchmarks-make_first-ordered: sub-tests-make_first-ordered  FORCE
	@test -d benchmarks/ || mkdir -p benchmarks/
	cd benchmarks/ && ( test -e Makefile || $(QMAKE) /home/sigve/Dropbox/Programs/PDtools/PDtools/benchmarks/benchmarks.pro -o Makefile ) && $(MAKE) -f Makefile 
sub-benchmarks-make_first: FORCE
	@test -d benchmarks/ || mkdir -p benchmarks/
	cd benchmarks/ && ( test -e Makefile || $(QMAKE) /home/sigve/Dropbox/Programs/PDtools/PDtools/benchmarks/benchmarks.pro -o Makefile ) && $(MAKE) -f Makefile 
sub-benchmarks-all-ordered: sub-tests-all-ordered  FORCE
	@test -d benchmarks/ || mkdir -p benchmarks/
	cd benchmarks/ && ( test -e Makefile || $(QMAKE) /home/sigve/Dropbox/Programs/PDtools/PDtools/benchmarks/benchmarks.pro -o Makefile ) && $(MAKE) -f Makefile all
sub-benchmarks-all: FORCE
	@test -d benchmarks/ || mkdir -p benchmarks/
	cd benchmarks/ && ( test -e Makefile || $(QMAKE) /home/sigve/Dropbox/Programs/PDtools/PDtools/benchmarks/benchmarks.pro -o Makefile ) && $(MAKE) -f Makefile all
sub-benchmarks-clean-ordered: sub-tests-clean-ordered  FORCE
	@test -d benchmarks/ || mkdir -p benchmarks/
	cd benchmarks/ && ( test -e Makefile || $(QMAKE) /home/sigve/Dropbox/Programs/PDtools/PDtools/benchmarks/benchmarks.pro -o Makefile ) && $(MAKE) -f Makefile clean
sub-benchmarks-clean: FORCE
	@test -d benchmarks/ || mkdir -p benchmarks/
	cd benchmarks/ && ( test -e Makefile || $(QMAKE) /home/sigve/Dropbox/Programs/PDtools/PDtools/benchmarks/benchmarks.pro -o Makefile ) && $(MAKE) -f Makefile clean
sub-benchmarks-distclean-ordered: sub-tests-distclean-ordered  FORCE
	@test -d benchmarks/ || mkdir -p benchmarks/
	cd benchmarks/ && ( test -e Makefile || $(QMAKE) /home/sigve/Dropbox/Programs/PDtools/PDtools/benchmarks/benchmarks.pro -o Makefile ) && $(MAKE) -f Makefile distclean
sub-benchmarks-distclean: FORCE
	@test -d benchmarks/ || mkdir -p benchmarks/
	cd benchmarks/ && ( test -e Makefile || $(QMAKE) /home/sigve/Dropbox/Programs/PDtools/PDtools/benchmarks/benchmarks.pro -o Makefile ) && $(MAKE) -f Makefile distclean
sub-benchmarks-install_subtargets-ordered: sub-tests-install_subtargets-ordered  FORCE
	@test -d benchmarks/ || mkdir -p benchmarks/
	cd benchmarks/ && ( test -e Makefile || $(QMAKE) /home/sigve/Dropbox/Programs/PDtools/PDtools/benchmarks/benchmarks.pro -o Makefile ) && $(MAKE) -f Makefile install
sub-benchmarks-install_subtargets: FORCE
	@test -d benchmarks/ || mkdir -p benchmarks/
	cd benchmarks/ && ( test -e Makefile || $(QMAKE) /home/sigve/Dropbox/Programs/PDtools/PDtools/benchmarks/benchmarks.pro -o Makefile ) && $(MAKE) -f Makefile install
sub-benchmarks-uninstall_subtargets-ordered: sub-tests-uninstall_subtargets-ordered  FORCE
	@test -d benchmarks/ || mkdir -p benchmarks/
	cd benchmarks/ && ( test -e Makefile || $(QMAKE) /home/sigve/Dropbox/Programs/PDtools/PDtools/benchmarks/benchmarks.pro -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-benchmarks-uninstall_subtargets: FORCE
	@test -d benchmarks/ || mkdir -p benchmarks/
	cd benchmarks/ && ( test -e Makefile || $(QMAKE) /home/sigve/Dropbox/Programs/PDtools/PDtools/benchmarks/benchmarks.pro -o Makefile ) && $(MAKE) -f Makefile uninstall

Makefile: PDtools-X10.pro .qmake.conf .qmake.cache /home/sigve/Qt/5.4/gcc_64/mkspecs/linux-g++/qmake.conf /home/sigve/Qt/5.4/gcc_64/mkspecs/features/spec_pre.prf \
		/home/sigve/Qt/5.4/gcc_64/mkspecs/common/shell-unix.conf \
		/home/sigve/Qt/5.4/gcc_64/mkspecs/common/unix.conf \
		/home/sigve/Qt/5.4/gcc_64/mkspecs/common/linux.conf \
		/home/sigve/Qt/5.4/gcc_64/mkspecs/common/gcc-base.conf \
		/home/sigve/Qt/5.4/gcc_64/mkspecs/common/gcc-base-unix.conf \
		/home/sigve/Qt/5.4/gcc_64/mkspecs/common/g++-base.conf \
		/home/sigve/Qt/5.4/gcc_64/mkspecs/common/g++-unix.conf \
		/home/sigve/Qt/5.4/gcc_64/mkspecs/qconfig.pri \
		/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_core.pri \
		/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri \
		/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_enginio.pri \
		/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri \
		/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_help.pri \
		/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_location.pri \
		/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_network.pri \
		/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_script.pri \
		/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri \
		/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/home/sigve/Qt/5.4/gcc_64/mkspecs/features/qt_functions.prf \
		/home/sigve/Qt/5.4/gcc_64/mkspecs/features/qt_config.prf \
		/home/sigve/Qt/5.4/gcc_64/mkspecs/linux-g++/qmake.conf \
		/home/sigve/Qt/5.4/gcc_64/mkspecs/features/spec_post.prf \
		.qmake.conf \
		.qmake.cache \
		/home/sigve/Qt/5.4/gcc_64/mkspecs/features/exclusive_builds.prf \
		/home/sigve/Qt/5.4/gcc_64/mkspecs/features/default_pre.prf \
		PDtools.pro \
		/home/sigve/Qt/5.4/gcc_64/mkspecs/features/resolve_config.prf \
		/home/sigve/Qt/5.4/gcc_64/mkspecs/features/default_post.prf \
		/home/sigve/Qt/5.4/gcc_64/mkspecs/features/warn_on.prf \
		/home/sigve/Qt/5.4/gcc_64/mkspecs/features/testcase_targets.prf \
		/home/sigve/Qt/5.4/gcc_64/mkspecs/features/exceptions.prf \
		/home/sigve/Qt/5.4/gcc_64/mkspecs/features/yacc.prf \
		/home/sigve/Qt/5.4/gcc_64/mkspecs/features/lex.prf \
		PDtools-X10.pro
	$(QMAKE) -o Makefile PDtools-X10.pro
/home/sigve/Qt/5.4/gcc_64/mkspecs/features/spec_pre.prf:
/home/sigve/Qt/5.4/gcc_64/mkspecs/common/shell-unix.conf:
/home/sigve/Qt/5.4/gcc_64/mkspecs/common/unix.conf:
/home/sigve/Qt/5.4/gcc_64/mkspecs/common/linux.conf:
/home/sigve/Qt/5.4/gcc_64/mkspecs/common/gcc-base.conf:
/home/sigve/Qt/5.4/gcc_64/mkspecs/common/gcc-base-unix.conf:
/home/sigve/Qt/5.4/gcc_64/mkspecs/common/g++-base.conf:
/home/sigve/Qt/5.4/gcc_64/mkspecs/common/g++-unix.conf:
/home/sigve/Qt/5.4/gcc_64/mkspecs/qconfig.pri:
/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri:
/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_core.pri:
/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_declarative.pri:
/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri:
/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_designer.pri:
/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_enginio.pri:
/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri:
/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_gui.pri:
/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_help.pri:
/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_location.pri:
/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_location_private.pri:
/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_network.pri:
/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_qml.pri:
/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_quick.pri:
/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_script.pri:
/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_script_private.pri:
/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri:
/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_sql.pri:
/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_svg.pri:
/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webchannel.pri:
/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri:
/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webengine.pri:
/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri:
/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri:
/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webkit.pri:
/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri:
/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webview.pri:
/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_webview_private.pri:
/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_xml.pri:
/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/home/sigve/Qt/5.4/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/home/sigve/Qt/5.4/gcc_64/mkspecs/features/qt_functions.prf:
/home/sigve/Qt/5.4/gcc_64/mkspecs/features/qt_config.prf:
/home/sigve/Qt/5.4/gcc_64/mkspecs/linux-g++/qmake.conf:
/home/sigve/Qt/5.4/gcc_64/mkspecs/features/spec_post.prf:
.qmake.conf:
.qmake.cache:
/home/sigve/Qt/5.4/gcc_64/mkspecs/features/exclusive_builds.prf:
/home/sigve/Qt/5.4/gcc_64/mkspecs/features/default_pre.prf:
PDtools.pro:
/home/sigve/Qt/5.4/gcc_64/mkspecs/features/resolve_config.prf:
/home/sigve/Qt/5.4/gcc_64/mkspecs/features/default_post.prf:
/home/sigve/Qt/5.4/gcc_64/mkspecs/features/warn_on.prf:
/home/sigve/Qt/5.4/gcc_64/mkspecs/features/testcase_targets.prf:
/home/sigve/Qt/5.4/gcc_64/mkspecs/features/exceptions.prf:
/home/sigve/Qt/5.4/gcc_64/mkspecs/features/yacc.prf:
/home/sigve/Qt/5.4/gcc_64/mkspecs/features/lex.prf:
PDtools-X10.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile PDtools-X10.pro

qmake_all: sub-src-qmake_all sub-tests-qmake_all sub-benchmarks-qmake_all FORCE

make_first: sub-src-make_first-ordered sub-tests-make_first-ordered sub-benchmarks-make_first-ordered FORCE
all: sub-src-all-ordered sub-tests-all-ordered sub-benchmarks-all-ordered FORCE
clean: sub-src-clean-ordered sub-tests-clean-ordered sub-benchmarks-clean-ordered FORCE
distclean: sub-src-distclean-ordered sub-tests-distclean-ordered sub-benchmarks-distclean-ordered FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-src-install_subtargets-ordered sub-tests-install_subtargets-ordered sub-benchmarks-install_subtargets-ordered FORCE
uninstall_subtargets: sub-src-uninstall_subtargets-ordered sub-tests-uninstall_subtargets-ordered sub-benchmarks-uninstall_subtargets-ordered FORCE

sub-src-check_ordered:
	@test -d src/ || mkdir -p src/
	cd src/ && ( test -e Makefile || $(QMAKE) /home/sigve/Dropbox/Programs/PDtools/PDtools/src/src.pro -o Makefile ) && $(MAKE) -f Makefile check
sub-tests-check_ordered: sub-src-check_ordered 
	@test -d tests/ || mkdir -p tests/
	cd tests/ && ( test -e Makefile || $(QMAKE) /home/sigve/Dropbox/Programs/PDtools/PDtools/tests/tests.pro -o Makefile ) && $(MAKE) -f Makefile check
sub-benchmarks-check_ordered: sub-tests-check_ordered 
	@test -d benchmarks/ || mkdir -p benchmarks/
	cd benchmarks/ && ( test -e Makefile || $(QMAKE) /home/sigve/Dropbox/Programs/PDtools/PDtools/benchmarks/benchmarks.pro -o Makefile ) && $(MAKE) -f Makefile check
check: sub-src-check_ordered sub-tests-check_ordered sub-benchmarks-check_ordered
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: sub-src-distdir sub-tests-distdir sub-benchmarks-distdir FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents .qmake.conf PDtools.pro PDtools-X10.pro $(DISTDIR)/

sub-src-distdir: FORCE
	@test -d src/ || mkdir -p src/
	cd src/ && ( test -e Makefile || $(QMAKE) /home/sigve/Dropbox/Programs/PDtools/PDtools/src/src.pro -o Makefile ) && $(MAKE) -e -f Makefile distdir DISTDIR=$(DISTDIR)/src

sub-tests-distdir: FORCE
	@test -d tests/ || mkdir -p tests/
	cd tests/ && ( test -e Makefile || $(QMAKE) /home/sigve/Dropbox/Programs/PDtools/PDtools/tests/tests.pro -o Makefile ) && $(MAKE) -e -f Makefile distdir DISTDIR=$(DISTDIR)/tests

sub-benchmarks-distdir: FORCE
	@test -d benchmarks/ || mkdir -p benchmarks/
	cd benchmarks/ && ( test -e Makefile || $(QMAKE) /home/sigve/Dropbox/Programs/PDtools/PDtools/benchmarks/benchmarks.pro -o Makefile ) && $(MAKE) -e -f Makefile distdir DISTDIR=$(DISTDIR)/benchmarks

